Feature/sign-up - 회원가입 및 회원정보 입력 페이지 구현
Docent-Inc/Docent-Front pull request #39
Opened 2023-11-12 11:34 UTC by Doyu-Lee

## 📌 제목
회원가입 및 회원정보 입력 페이지 구현

<br />

## ✨ 작업 내용
- 폰트 전역 변수 추가

|로그인/회원가입 페이지| 회원 정보 입력|
|---|---|
|<img width="327" alt="image" src="https://github.com/Docent-Inc/Docent-Front/assets/125176463/93192aa8-95f9-48c6-b9e3-dc63a8998581">|![시연영상](https://github.com/Docent-Inc/Docent-Front/assets/125176463/27b60867-1fd0-43c9-89b8-6a05a8cf953a)|

<br />

## 🚨 요청 사항 / 유의 사항
- 프로필 생성 `profile/starter`, 프로필 수정 `profile/modify (전: /modify-profile)` path 변경되었습니다.

2023-11-12 15:03 UTC, yusiny requested changes
시맨틱 태그들 사용하시는 거나, CSS 사용하시는 방식 보고 많이 배워갑니다 ㅎㅎ 
고생 많으셨어요 😀

margin 관련 리뷰들은 한번 확인 부탁드려요, mbti 쪽 로직 관련한 건 단순 의견이고 궁금한 거여서 한번 읽어만 봐주셔도 좋을 것 같습니다
margin 쪽 수정된 것만 확인되면 바로 머지되어도 좋을 것 같습니다!

2023-11-12 15:03 UTC, yusiny commented on components/signup/SignUpMBTI.vue
> +.mbti-box {
화면 상으로 봤을 때 MBTI, 박스 간의 간격이 살짝 좁아보이는 데 디자인 상으로 margin-top: 12px 있지 않나요?

2023-11-12 15:03 UTC, yusiny commented on components/signup/SignUpMBTI.vue
> +            selected: {},
처음 들어갔을 때 기본 선택값이 있는 건 어떨까요? 상단에 있는 ENFP 이런 정도로...

2023-11-12 15:03 UTC, yusiny commented on components/signup/SignUpNickname.vue
> +            } else {
이건 디자이너님한테도 여쭤봐야 할 것 같기는 한데, 보통 validation 실패했을 경우에도 빨간색으로 메시지 띄워주잖아요 
그런 것들도 나중에 추가하면 어떨까요? 지금 당장 생각나는 건 글자 수 6자 제한이 있는 것 같은데 입력만 막히고 아래 문구는 그대로 "멋진 이름이네요!"여서,  "6자 이하로 입력해 주세요." 등과 같이 validation 실패 문구도 나중에 추가되면 어떨까 ㅎㅎ 의견 남겨봅니다

2023-11-12 15:03 UTC, yusiny commented on components/signup/SignUpGender.vue
> +.gender-box {
여기도 마찬가지로 제목과 간격이 없는데, margin-top; 8px; 안 들어간 거 아닐까요?

2023-11-12 15:03 UTC, yusiny commented on components/signup/SignUpGender.vue
> +            selectedGender: null,
성별도 개인적으로 기본값 설정되어있으면 어떨까 의견 남겨봅니다!

2023-11-12 15:03 UTC, yusiny commented on components/signup/SignUpMBTI.vue
> +        <div v-for="pair in mbtiPairs" :key="pair.primary" class="mbti-pair">
오... 이거 코드를 이렇게 짜셨군요! 신기하네요 
이건 그냥 궁금한 건데, html보다는 script 단 로직에서 처리하는 걸 선호하시나요?
저는 이렇게 MBTI 같은 건, 어느정도 정해져 있는 거니 차라리 html에 하드코딩 해 두고 선택된 값 변동되는 것들만 script에 넣었을 것 같거든요! 저랑 스타일이 다른 것 같아 궁금해서 여쭤봅니다 ㅎㅎ

2023-11-12 15:03 UTC, yusiny commented on components/signup/SignUpMBTI.vue
> +        toggleSelection(primary, value, opposite) {
이것도 위 코멘트랑 같은 맥락이긴 한데, 사실 처음 이쪽 코드 봤을 땐 이해하기가 조금 어렵더라구요
매 변경 시마다 mbtiOrder 반복문 돌면서 정렬해서 내보내주는 게 좋을까? 하는 생각이 조금 들기는 하네요 

뭔가 저라면 selected: ['E', 'N', 'F', 'P'] 이런 식으로 배열로 해서 
변경될 때마다 toggleSelection에 (해당 pair idx, option value) 정도 넘겨서 
selected[pair idx] = option value 이런 식으로 변경해 주고
return은 selected.join() 해서 보내버릴 것 같다는 의견,, 살짝 남겨봅니다 ㅎㅎ 

이쪽 코드는 후에 알아보기 쉽게 작성하신 로직이라도 노션에 적어주시거나 하셔도 좋을 것 같습니다!

2023-11-12 15:03 UTC, yusiny commented on pages/signin/index.vue
> +                <v-icon alt="Look Logo" class="logo_look_white" />
오 ㅎㅎ alt 태그 저 한번도 사용 안 했었는데, 이미지 부분에서는 저도 사용해 보는 게 좋긴 하겠네요 
v-icon에서도 alt 태그가 정상 동작 하나요? 제가 만든 Icon 컴포넌트가 있긴 한데, 이건 div 태그라서요 
후에 img 태그로 변경해 볼까요? 

시맨틱 태그들 잘 사용하시네요,, 저도 나중엔 반영해 보아야겠어요 👍

2023-11-13 00:34 UTC, Doyu-Lee commented on components/signup/SignUpMBTI.vue
> +.mbti-box {
아앗- 네 수정했습니당

2023-11-13 00:38 UTC, Doyu-Lee commented on components/signup/SignUpNickname.vue
> +            } else {
저도 늘 validation까지 적용을 시켰어서 이 생각이 제일 먼저 들긴 했는데 현재 룩 앱의 경우, 딱히 닉네임 형식에 제한이 없어서 추후 유저 테스트 단계에서 조금 더 구체적으로 이야기 나오면 좋을 것 같아요-! (필요하다면 특수기호 제한이나..)

글자수 제한은 `닉네임은 6자 이내로 입력해주세요`라고 place-holder에 적혀있고, 6자 초과가 되지 않도록 입력이 막혀 있어서 에러 메시지가 출력될 상황은 아직은 필요하지 않을 것 같습니다 ☺️

2023-11-13 00:39 UTC, Doyu-Lee commented on components/signup/SignUpGender.vue
> +.gender-box {
네네 ㅠㅠ 마지막에 구조를 바꾸면서 css 적용을 안 시켰네요 감사해요!!!

2023-11-13 00:41 UTC, Doyu-Lee commented on components/signup/SignUpGender.vue
> +            selectedGender: null,
기본값 설정은 **값 입력을 안 했을 때** 다음 또는 가입 완료 버튼이 `disabled` 속성을 가지기 위함인데, 혹시 이 방식 말고 버튼 비활성 상태를 구현할 수 있는 좋은 의견 있으실까요?!

2023-11-13 00:43 UTC, Doyu-Lee commented on components/signup/SignUpMBTI.vue
> +        <div v-for="pair in mbtiPairs" :key="pair.primary" class="mbti-pair">
추후 확장성을 고려하여 재사용 가능할 만한 컴포넌트 구조를 생각하여 짜는 편이라서 map 함수로 들어갈 수 있는 데이터들은 웬만하면 그렇게 넣는 편 같아요!

2023-11-13 00:49 UTC, Doyu-Lee commented on pages/signin/index.vue
> +                <v-icon alt="Look Logo" class="logo_look_white" />
아! 안 그래도 이 부분 작업하면서 말씀 드리고 싶었는데, 작은 아이콘 제외하고 LOOK 등의 로고 정도는 일괄적으로 image 태그로 사용하는 것이 어떨까요?!

2023-11-13 00:56 UTC, Doyu-Lee commented on components/signup/SignUpMBTI.vue
> +        toggleSelection(primary, value, opposite) {
네 기존 코드가 그런 식으로 되어 있더라고요! 다른 곳에서도 적용 가능하게 폭 넓게 작성했는데 말씀하는 방식으로도 적용 가능하면 바꿔볼게요!

2023-11-13 01:00 UTC, merged