Feature/terms - 약관 페이지 구현
Docent-Inc/Docent-Front pull request #63
Opened 2023-11-22 03:04 UTC by Doyu-Lee

## 📌 제목
Feature/terms - 약관 페이지 구현

<br />

## ✨ 작업 내용
### 1. 약관 페이지 생성
### 2. QA 이슈 해결 
 - **[ID-3]**,  **[ID-4]**, **[ID-6]**, **[ID-7]** : 문구 수정
 - **[ID-8]** : 생년월일 스크롤 부드럽게 수정 
 - **[ID-9]** : 홈화면에 요일 추가
 - **[ID-40]** : '캘린더 보러가기', '기록 보러가기' 폰트 적용
 - **[ID-41]** : 기록 컴포넌트에 기본 이미지 출력 
  
<br />

|약관 페이지|280px|
|---|---|
|![약관](https://github.com/Docent-Inc/Docent-Front/assets/125176463/621d6c5b-8348-490a-8734-e1b9f78aa378)|<img width="350" alt="image" src="https://github.com/Docent-Inc/Docent-Front/assets/125176463/10935d0b-10e7-4af5-8509-b60108f76786">|
|홈 화면 날씨(가입 후 초기상태)|생년월일|
|<img width="491" alt="image" src="https://github.com/Docent-Inc/Docent-Front/assets/125176463/47ac6e5c-33e0-4624-93a7-af32c356a67d">|![생년월일](https://github.com/Docent-Inc/Docent-Front/assets/125176463/6fb47361-40dd-406e-a46b-8e44cccddbd6)|

<br />

## 🚨 요청 사항 / 유의 사항
- [ ] 이슈 생성자(서준님) 생년월일 모바일 환경에서 테스트 요망
- [ ] 운세 팝업 바텀 노출 ios 환경에서 테스트 필요 
- [ ] 이슈 생성자(유신님) '캘린더 보러가기' 등 폰트 확인 테스트 요망 

<br />

## 📚 참고
 - [QA 노션 링크](https://www.notion.so/docent-ai/QA-7630948862524c33989cdbf49ee8f2fa)

2023-11-22 14:26 UTC, yusiny requested changes
브랜치 main으로 설정되어 있는 것 같고,
제가 작업한 fix/auth 머지된 후에는 utils/axios.js 파일 없어질 거라 API 호출하는 부분 services/index.ts의 인스턴스 사용하는 걸로 변경하셔야 할 거 같아요
(이건 제 거 머지되면 develop 한번 pull 받아서 수정하시는 거 추천드려요!)

나머지는 마찬가지로 단순 의견 정도의,, 리뷰입니다
고생 많으셨어요 👍

2023-11-22 14:26 UTC, yusiny commented on components/signup/SignUpTerms.vue
> +            const parts = label.split("/");
이게 /텍스트/ 로 감싸진 부분 처리하려고 해두신 거 맞을까요~?
맞다면 저는 이런 상황에서 정규식을 활용하기도 하는데요! 그 방법도 생각해 보시면 어떨까요~?

```
// components/chat/ExampleChatBox.vue - *텍스트* 작업했던 예시입니다~
 processedText() {
        return this.chat.text.replace(
            /\*(.*?)\*/g,
            '<span style="color: #6366f1;">$1</span>',
        );
},
```

2023-11-22 14:26 UTC, yusiny commented on components/signup/SignUpTerms.vue
> +                newTab.referrerPolicy = "no-referrer";
이거는 혹시 설정하신 이유가 뭘까요~? 궁금해서 ㅎㅎ

2023-11-22 14:26 UTC, yusiny commented on pages/profile/starter.vue
> +                    <SignUpTerms @all-checkboxes-checked="handleAllCheck" />
이건 그냥 제 개인적인 취향,,? 같은 건데요 
저는 emit 할 때 최대한 간결하게 하는 걸 선호해서 저라면 @checked 이런 식으로 했을 거 같아요 
역시 코드 짜는 방식은 다 다르네요 ㅎㅎ

2023-11-22 14:26 UTC, yusiny commented on services/today.ts
> +        async getTodayWeather(lat: string, lon: string) {
여기도 /utils/axios.js API 인스턴스 사용하는 거 같은데, 제 거 develop 머지되면 바꿔야 할 거 같네요...!

2023-11-22 14:26 UTC, yusiny commented on utils/utils.js
> +            reject(new Error("Geolocation is not supported"));
이 경우에는 어떻게 처리되나요? API 호출만 안되나요?

2023-11-23 08:01 UTC, Doyu-Lee commented on components/signup/SignUpTerms.vue
> +                newTab.referrerPolicy = "no-referrer";
보안 상 이유로 걸어두었습니다!

2023-11-23 08:01 UTC, Doyu-Lee commented on pages/profile/starter.vue
> +                    <SignUpTerms @all-checkboxes-checked="handleAllCheck" />
오호 간결하게 하시는 이유가 따로 있으실까요? 저는.. 일주일 뒤의 저를 믿지 않기에...ㅋㅋㅋ 최대한 자세하게 넣는 편입니다ㅋㅋㅋ 😂

2023-11-23 08:01 UTC, Doyu-Lee commented on utils/utils.js
> +            reject(new Error("Geolocation is not supported"));
오우~ 방금 화면에도 예외처리 해주고 왔습니다 감사해요!

2023-11-23 12:09 UTC, yusiny approved these changes

2023-11-23 12:25 UTC, merged